- name: Cleanup Azure Resources for Docker Cluster and Monitoring
  hosts: localhost
  connection: local
  vars_files:
    - secrets.yml
  tasks:

    - name: Remove virtual machines
      azure_rm_virtualmachine:
        resource_group: A2S2_groep_04
        name: "{{ item }}"
        state: absent
      loop:
        - Grafana
        - HAProxy
        - DockerMaster
        - DockerWorker

    - name: Remove network interfaces
      azure_rm_networkinterface:
        resource_group: A2S2_groep_04
        name: "{{ item }}"
        state: absent
      loop:
        - GrafanaNIC
        - HAProxyNIC
        - DockerMasterNIC
        - DockerWorkerNIC

    - name: Remove public IPs
      azure_rm_publicipaddress:
        resource_group: A2S2_groep_04
        name: "{{ item }}"
        state: absent
      loop:
        - GrafanaPublicIP
        - HAProxyPublicIP
        - DockerMasterPublicIP
        - DockerWorkerPublicIP

    - name: Remove network security groups
      azure_rm_securitygroup:
        resource_group: A2S2_groep_04
        name: "{{ item }}"
        state: absent
      loop:
        - GrafanaNetworkSecurityGroup
        - HAProxyNSG
        - DockerMasterNSG
        - DockerWorkerNSG

    - name: Remove subnet
      azure_rm_subnet:
        resource_group: A2S2_groep_04
        name: DockerSubnet
        virtual_network: DockerVnet
        state: absent

    - name: Remove virtual network
      azure_rm_virtualnetwork:
        resource_group: A2S2_groep_04
        name: DockerVnet
        state: absent
